baseURL = "https://vorsatzpapier.projektemacher.org/"
languageCode = "de"
title = "Vorsatzpapier"
theme = ["projektemacher-base", "hugo-nederburg-theme"]
publishDir = "docs"
canonifyurls = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
DefaultContentLanguage = "de"
rssLimit = 25
#copyright = false
timeout = 300
enableGitInfo = true
copyright = '<a href="https://projektemacher.org/" target="_blank">Projektemacher</a>'

[pagination]
  pagerSize = 10

[languages]
    [languages.de]
        languagename = "Deutsch"

        [languages.de.params]

        [languages.de.menu]

            [[languages.de.menu.main]]
                name = "Start"
                weight = 1
                url = "/"

            [[languages.de.menu.main]]
                name = "Weiterverwendung"
                weight = 2
                url = "reuse/"

            [[languages.de.menu.main]]
                name = "Muster"
                weight = 3
                url = "patterns/"

            [[languages.de.menu.main]]
                name = "Eigene Muster"
                weight = 4
                url = "generator/"
                [[languages.de.menu.main.params]]
                  draft = true

            [[languages.de.menu.main]]
                name = "Links"
                weight = 5
                url = "links/"

            [[languages.de.menu.main]]
                name = "Über"
                weight = 6
                url = "about/"

    [languages.en]
        languagename = "English"

        [languages.en.params]


        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "Start"
                weight = 1
                url = "/"

            [[languages.en.menu.main]]
                name = "Reuse"
                weight = 2
                url = "reuse/"

            [[languages.en.menu.main]]
                name = "Patterns"
                weight = 3
                url = "patterns/"

            [[languages.de.menu.main]]
                name = "Mustergenerator"
                weight = 4
                url = "generator/"
                [[languages.de.menu.main.params]]
                  draft = true

            [[languages.en.menu.main]]
                name = "Links"
                weight = 5
                url = "links/"

            [[languages.en.menu.main]]
                name = "About"
                weight = 6
                url = "about/"

[module]
  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "assets/js"
    target = "assets/js"

#[outputs]
#    page = ["HTML"]

[imaging]
    quality = 95

[mediaTypes]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
  # See https://www.loc.gov/preservation/digital/formats/fdd/fdd000538.shtml
  [mediaTypes."image/jxl"]
    suffixes = ["jxl"]

[outputFormats]
  [outputFormats.iiif]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-manifest]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "manifest"
    notAlternative = true

  [outputFormats.iiif-collection]
    mediaType = "application/ld+json"
    isPlainText = true
    isHTML = false
    baseName = "collection"
    notAlternative = true

[markup]
  defaultMarkdownHandler = 'goldmark'

[markup.goldmark]
    [markup.goldmark.renderer]
        unsafe= true

    [markup.goldmark.extensions]
        #typographer = true
        attribute = true
        strikethrough = true

  [markup.goldmark.extensions.typographer]
          apostrophe = '&rsquo;'
          disable = false
          ellipsis = '&hellip;'
          emDash = '&mdash;'
          enDash = '&ndash;'
          leftAngleQuote = '&laquo;'
          leftDoubleQuote = '&ldquo;'
          leftSingleQuote = '&lsquo;'
          rightAngleQuote = '&raquo;'
          rightDoubleQuote = '&rdquo;'
          rightSingleQuote = '&rsquo;'

[sitemap]
  changeFreq = 'weekly'

[build]
  writeStats = true

[[cascade]]
  outputs = ['html','rss', 'iiif-collection']
  [cascade._target]
    kind = "term"
    path = "/tags/**"
