baseURL = "https://vorsatzpapier.projektemacher.org/"
languageCode = "de"
title = "Vorsatzpapier"
theme = ["projektemacher-base", "hugo-nederburg-theme"]
publishDir = "docs"
canonifyurls = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
DefaultContentLanguage = "de"
rssLimit = 25
paginate = 10

[params]
    author = "Christian Mahnke"
    keywords = "Vorsatzpapiere, Ornamente, Papier, Bücher, Book end paper, paper, books"
    description = ""
#    copyrightYears = "MMXX"
    stylesheets = []
    iiifCanvasHeight = 400
    iiifCanvasWidth = 300
    productionIIIFURLPrefix="https://static.projektemacher.org/vorsatzpapier/"

[languages]
    [languages.de]
        languagename = "Deutsch"

        [languages.de.params]

        [languages.de.menu]

            [[languages.de.menu.main]]
                name = "Start"
                weight = 1
                url = "/"

            [[languages.de.menu.main]]
                name = "Weiterverwendung"
                weight = 2
                url = "reuse/"

            [[languages.de.menu.main]]
                name = "Muster"
                weight = 3
                url = "patterns/"

            [[languages.de.menu.main]]
                name = "Links"
                weight = 4
                url = "links/"

            [[languages.de.menu.main]]
                name = "Über"
                weight = 5
                url = "about/"

    [languages.en]
        languagename = "English"

        [languages.en.params]


        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "Start"
                weight = 1
                url = "/"

            [[languages.en.menu.main]]
                name = "Reuse"
                weight = 2
                url = "reuse/"

            [[languages.en.menu.main]]
                name = "Patterns"
                weight = 3
                url = "patterns/"

            [[languages.en.menu.main]]
                name = "Links"
                weight = 4
                url = "links/"

            [[languages.en.menu.main]]
                name = "About"
                weight = 5
                url = "about/"

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"

[outputs]
    page = ["HTML", "JSON"]

[imaging]
    quality = 95

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true
