baseURL = "https://vorsatzpapier.projektemacher.org/"
languageCode = "de"
title = "Vorsatzpapier"
theme = "hugo-nederburg-theme"
publishDir = "docs"
canonifyurls = true
disableKinds = ["term"]
DefaultContentLanguage = "de"
rssLimit = 25

[params]
    author = "Christian Mahnke"
    keywords = "Vorsatzpapiere, Ornamente, Papier, Bücher, Book end paper, paper, books"
    description = ""
    copyrightYears = "2020"
    stylesheets = ["https://fonts.googleapis.com/css?family=Raleway%3A400%2C700&amp;subset=latin%2Clatin-ext&amp;ver=4.7.2&display=swap"]


[languages]
    [languages.de]
        languagename = "Deutsch"

        [languages.de.params]

        [languages.de.menu]

            [[languages.de.menu.main]]
                name = "Start"
                weight = 1
                url = "/"

            [[languages.de.menu.main]]
                name = "Über"
                weight = 2
                url = "about/"

    [languages.en]
        languagename = "English"

        [languages.en.params]


        [languages.en.menu]

            [[languages.en.menu.main]]
                name = "Start"
                weight = 1
                url = "/"

            [[languages.de.menu.main]]
                name = "About"
                weight = 2
                url = "about/"

[module]
    [[module.mounts]]
        source = "assets/scss"
        target = "assets/scss"

    [[module.mounts]]
        source = "static"
        target = "static"

    [[module.mounts]]
        source = "node_modules/ol"
        target = "assets/css/ol"

    [[module.mounts]]
        source = "assets/js"
        target = "assets/js"


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true
