name: github pages

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 7 * * */2'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install required dependencies
        run: |
          ./themes/projektemacher-base/scripts/github/setup-dependencies.sh
          ./themes/projektemacher-base/scripts/github/python-dependencies.sh
          ./themes/projektemacher-base/scripts/github/setup-inkscape.sh
          ./themes/projektemacher-base/scripts/github/docker-images.sh

      - name: Setup deploy dependencies
        env:
          DEPLOY_SSH_IDENTITY: ${{ secrets.DEPLOY_SSH_IDENTITY }}
        run: |
          mkdir -p ~/.ssh && echo "$DEPLOY_SSH_IDENTITY" >>  ~/.ssh/known_hosts

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version-file: '.nvmrc'

      - name: Create IIIF derivates
        run: |
          echo "Running as ${UID}"
          docker run -e CHOWN_UID=${UID} -e URL_PREFIX="https://static.projektemacher.org/vorsatzpapier/" -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest sh -c "cd ${PWD} && ./scripts/iiif.sh"

      - name: IIIF directory upload and cleanup
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SSHPASS: ${{ secrets.DEPLOY_PASS }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          cd content
          find post -name info.json -exec dirname {} \; > files.lst
          cat files.lst | xargs chmod 775
          sshpass -e rsync -aP --size-only --delete --relative $(cat files.lst) $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH/vorsatzpapier/
          rm -f files.lst
          cd ..
          find content/post/ -name info.json -exec dirname {} \; | xargs rm -r

      - name: Generate Files
        env:
          SKIP_IIIF: yes
        run: |
          ./scripts/setup.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: '0.104.3'
          extended: true

      - name: Build Hugo site
        run: hugo --printI18nWarnings

      - name: Cleanup Build
        run: |
           find docs -type f -size +5M -name '*.jpg' -exec rm {} \;
           rm -rf docs/plugins

      - name: Validate JSON
        env:
          OSTYPE: linux
        run: |
          yarn run validate

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
