name: Publish on GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 3'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required dependencies
        run: |
          ./scripts/github-setup.sh

      - name: Setup deploy dependencies
        env:
          DEPLOY_SSH_IDENTITY: ${{ secrets.DEPLOY_SSH_IDENTITY }}
        run: |
          mkdir -p ~/.ssh && echo "$DEPLOY_SSH_IDENTITY" >>  ~/.ssh/known_hosts

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.nvmrc'

      - name: Create IIIF derivates
        run: |
          echo "Running as ${UID}"
          docker run -e CHOWN_UID=${UID} -e URL_PREFIX="https://static.projektemacher.org/vorsatzpapier/" -v ${PWD}:${PWD} ghcr.io/cmahnke/iiif-action:latest-jxl-uploader sh -c "cd ${PWD} && ./scripts/iiif.sh"

      - name: IIIF directory upload and cleanup
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SSHPASS: ${{ secrets.DEPLOY_PASS }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          cd content
          find post -name info.json -exec dirname {} \; > files.lst
          cat files.lst | xargs chmod 775
          sshpass -e rsync -aP --size-only --delete --relative $(cat files.lst) $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH/vorsatzpapier/
          rm -f files.lst
          cd ..
          find content/post/ -name info.json -exec dirname {} \; | xargs -I {} find {} -mindepth 1 -type d -not -path '*/full*' | xargs rm -fr
          #find content/post/ -name info.json -exec dirname {} \; | xargs rm -r
          #find content/post/ -name info.json -exec dirname {} \; | xargs -I{} find {} ! -ipath full/full/0/default.jpg | xargs rm -r

      - name: Generate Files
        env:
          SKIP_IIIF: yes
        run: |
          ./scripts/setup.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: '0.130.0'
          extended: true

      - name: Generate stats
        run: |
          ./themes/projektemacher-base/scripts/stat.sh

      - name: Build Hugo site
        run: hugo --printI18nWarnings

      - name: Cleanup Build
        run: |
           find docs -type f -size +5M -name '*.jpg' -exec rm {} \;
           rm -rf docs/plugins

      - name: Validate JSON
        env:
          OSTYPE: linux
        run: |
          yarn run validate

      - name: Puppeteer
        run: ./themes/projektemacher-base/scripts/github/check-js-errors.sh

      - name: Archive links
        run: python ./themes/projektemacher-base/scripts/archive.py -d docs/ -e vorsatzpapier.projektemacher.org,projektemacher.org

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
